{
  "AVAXUSDT": {
    "break_even_enabled": 0,
    "break_even_offset_bps": 2.8959529929128545,
    "break_even_trigger_r": 0.46029205743942625,
    "constraints": {
      "max_fill_delay_min": 60.0,
      "max_taker_share": 0.25,
      "min_entry_rate": 0.93,
      "min_median_entry_improvement_bps": 0.0
    },
    "cooldown_min": 19,
    "entry_mode": "limit",
    "exec_mode": "ga_exec_3m_opt",
    "fallback_delay_min": 1,
    "fallback_to_market": 0,
    "killzone_filter": 0,
    "limit_offset_bps": 25.95721662258688,
    "max_fill_delay_min": 36,
    "micro_vol_filter": 0,
    "min_entry_improvement_bps_gate": 2.2498176762220767,
    "mss_displacement_gate": 0,
    "partial_take_enabled": 1,
    "partial_take_pct": 0.9,
    "partial_take_r": 1.4400475301317872,
    "skip_if_vol_gate": 1,
    "sl_mult": 1.7638669419193769,
    "spread_guard_bps": 55.35187970977983,
    "time_stop_min": 3241,
    "tp_mult": 2.3879247906683196,
    "trail_start_r": 0.9678355158463121,
    "trail_step_bps": 17.252937867664194,
    "trailing_enabled": 0,
    "vol_threshold": 1.4222710450176481
  },
  "NEARUSDT": {
    "break_even_enabled": 0,
    "break_even_offset_bps": 2.8959529929128545,
    "break_even_trigger_r": 0.46029205743942625,
    "constraints": {
      "max_fill_delay_min": 45.0,
      "max_taker_share": 0.3,
      "min_entry_rate": 0.95,
      "min_median_entry_improvement_bps": 0.0
    },
    "cooldown_min": 19,
    "entry_mode": "limit",
    "exec_mode": "ga_exec_3m_opt",
    "fallback_delay_min": 1,
    "fallback_to_market": 0,
    "killzone_filter": 0,
    "limit_offset_bps": 25.95721662258688,
    "max_fill_delay_min": 36,
    "micro_vol_filter": 0,
    "min_entry_improvement_bps_gate": 2.2498176762220767,
    "mss_displacement_gate": 0,
    "partial_take_enabled": 1,
    "partial_take_pct": 0.9,
    "partial_take_r": 1.4400475301317872,
    "skip_if_vol_gate": 1,
    "sl_mult": 1.7638669419193769,
    "spread_guard_bps": 55.35187970977983,
    "time_stop_min": 3241,
    "tp_mult": 2.3879247906683196,
    "trail_start_r": 0.9678355158463121,
    "trail_step_bps": 17.252937867664194,
    "trailing_enabled": 0,
    "vol_threshold": 1.4222710450176481
  },
  "SOLUSDT": {
    "break_even_enabled": 0,
    "break_even_offset_bps": 2.8959529929128545,
    "break_even_trigger_r": 0.46029205743942625,
    "constraints": {
      "max_fill_delay_min": 45.0,
      "max_taker_share": 0.25,
      "min_entry_rate": 0.97,
      "min_median_entry_improvement_bps": 0.0
    },
    "cooldown_min": 19,
    "entry_mode": "limit",
    "exec_mode": "ga_exec_3m_opt",
    "fallback_delay_min": 1,
    "fallback_to_market": 0,
    "killzone_filter": 0,
    "limit_offset_bps": 25.95721662258688,
    "max_fill_delay_min": 36,
    "micro_vol_filter": 0,
    "min_entry_improvement_bps_gate": 2.2498176762220767,
    "mss_displacement_gate": 0,
    "partial_take_enabled": 1,
    "partial_take_pct": 0.9,
    "partial_take_r": 1.4400475301317872,
    "skip_if_vol_gate": 1,
    "sl_mult": 1.7638669419193769,
    "spread_guard_bps": 55.35187970977983,
    "time_stop_min": 3241,
    "tp_mult": 2.3879247906683196,
    "trail_start_r": 0.9678355158463121,
    "trail_step_bps": 17.252937867664194,
    "trailing_enabled": 0,
    "vol_threshold": 1.4222710450176481
  }
}