{
  "AVAXUSDT": {
    "break_even_enabled": 0,
    "break_even_offset_bps": 1.238019611496456,
    "break_even_trigger_r": 1.2835651558400476,
    "constraints": {
      "max_fill_delay_min": 60.0,
      "max_taker_share": 0.25,
      "min_entry_rate": 0.93,
      "min_median_entry_improvement_bps": 0.0
    },
    "cooldown_min": 34,
    "entry_mode": "limit",
    "exec_mode": "ga_exec_3m_opt",
    "fallback_delay_min": 9,
    "fallback_to_market": 0,
    "killzone_filter": 0,
    "limit_offset_bps": 28.435960818271898,
    "max_fill_delay_min": 25,
    "micro_vol_filter": 0,
    "min_entry_improvement_bps_gate": 1.7189446737834335,
    "mss_displacement_gate": 0,
    "partial_take_enabled": 0,
    "partial_take_pct": 0.4173443797206241,
    "partial_take_r": 0.9925235383409983,
    "skip_if_vol_gate": 0,
    "sl_mult": 0.7091271002159425,
    "spread_guard_bps": 2.3199569909882722,
    "time_stop_min": 3477,
    "tp_mult": 1.5454303784268988,
    "trail_start_r": 1.4459388735976058,
    "trail_step_bps": 29.56684831855996,
    "trailing_enabled": 0,
    "vol_threshold": 2.0970667507377567
  },
  "NEARUSDT": {
    "break_even_enabled": 0,
    "break_even_offset_bps": 1.238019611496456,
    "break_even_trigger_r": 1.2835651558400476,
    "constraints": {
      "max_fill_delay_min": 45.0,
      "max_taker_share": 0.3,
      "min_entry_rate": 0.95,
      "min_median_entry_improvement_bps": 0.0
    },
    "cooldown_min": 34,
    "entry_mode": "limit",
    "exec_mode": "ga_exec_3m_opt",
    "fallback_delay_min": 9,
    "fallback_to_market": 0,
    "killzone_filter": 0,
    "limit_offset_bps": 28.435960818271898,
    "max_fill_delay_min": 25,
    "micro_vol_filter": 0,
    "min_entry_improvement_bps_gate": 1.7189446737834335,
    "mss_displacement_gate": 0,
    "partial_take_enabled": 0,
    "partial_take_pct": 0.4173443797206241,
    "partial_take_r": 0.9925235383409983,
    "skip_if_vol_gate": 0,
    "sl_mult": 0.7091271002159425,
    "spread_guard_bps": 2.3199569909882722,
    "time_stop_min": 3477,
    "tp_mult": 1.5454303784268988,
    "trail_start_r": 1.4459388735976058,
    "trail_step_bps": 29.56684831855996,
    "trailing_enabled": 0,
    "vol_threshold": 2.0970667507377567
  },
  "SOLUSDT": {
    "break_even_enabled": 0,
    "break_even_offset_bps": 1.238019611496456,
    "break_even_trigger_r": 1.2835651558400476,
    "constraints": {
      "max_fill_delay_min": 45.0,
      "max_taker_share": 0.25,
      "min_entry_rate": 0.97,
      "min_median_entry_improvement_bps": 0.0
    },
    "cooldown_min": 34,
    "entry_mode": "limit",
    "exec_mode": "ga_exec_3m_opt",
    "fallback_delay_min": 9,
    "fallback_to_market": 0,
    "killzone_filter": 0,
    "limit_offset_bps": 28.435960818271898,
    "max_fill_delay_min": 25,
    "micro_vol_filter": 0,
    "min_entry_improvement_bps_gate": 1.7189446737834335,
    "mss_displacement_gate": 0,
    "partial_take_enabled": 0,
    "partial_take_pct": 0.4173443797206241,
    "partial_take_r": 0.9925235383409983,
    "skip_if_vol_gate": 0,
    "sl_mult": 0.7091271002159425,
    "spread_guard_bps": 2.3199569909882722,
    "time_stop_min": 3477,
    "tp_mult": 1.5454303784268988,
    "trail_start_r": 1.4459388735976058,
    "trail_step_bps": 29.56684831855996,
    "trailing_enabled": 0,
    "vol_threshold": 2.0970667507377567
  }
}